### ISSUE TITLE
How to show FIX format

### ISSUE THREAD

**Issue by veltmannb** [GaryHughes/FixMaster#14]
Hi, looks cool! Beginner's question. How to show FIX format, when I choose a row from the log (35=D in screenshot) and choose via right click, nothing happens?
Thanks in advance, kind Regards, Bernhard
![FIXMASTER](https://user-images.githubusercontent.com/55944355/65830188-8fb90e00-e2ad-11e9-80d0-0672edbd21c7.png)

**Comment by GaryHughes** [comment]
It currently processes the whole file not just the selection, open the command pallete from the view menu or press ctrl-shift-p and type ’fix’, the command ‘FIX Protocol format’ will appear, select it and hit enter.

**Comment by veltmannb** [comment]
![fix](https://user-images.githubusercontent.com/55944355/65867679-28679080-e377-11e9-8949-318ed2506f2d.PNG)

**Comment by GaryHughes** [comment]
Hi, should I infer that you have it working given that the issue is closed? If not please attach a sample log and I'll have a look.

**Comment by veltmannb** [comment]
[FIX.log](https://github.com/GaryHughes/FixMaster/files/3670201/FIX.log)

**Comment by GaryHughes** [comment]
There is a bug in the message detection, I'd only tested on versions with a BeginString of FIX.N.N and your FIXT.1.1 BeginStrings are causing the detection to fail.

I'll fix and publish a new version shortly.

**Comment by GaryHughes** [comment]
Thats fixed and I've published a new version, not sure how long it will take to be available but it should only be a few minutes.

If you change the Prefix Pattern setting to the following regex it will extract your timestamps correctly as well.

\d{8}-\d{2}:\d{2}:\d{2}\.\d+
