### ISSUE TITLE
Column Seperators between Tag - Field Name - Value - Desc - Type

### ISSUE THREAD

**Issue by veltmannb** [GaryHughes/FixMaster#19]
Probably covered by issue "Support a configurable field separator"? Couldn't manage to make a quick copy paste into Excel.  Separators missing for "text to columns".? Would look like attached.

![FIXExcel](https://user-images.githubusercontent.com/55944355/65878661-ddf20e00-e38e-11e9-8f84-fd782fca48b2.PNG)

**Comment by GaryHughes** [comment]
The configurable field separator is just for parsing but I can add a similar option for output as well to support copy and paste like this.

**Comment by veltmannb** [comment]
I'd like this feature. Find it helpful for documenting purposes and comparing or mapping standards, e.g. SWIFT <> FIX

**Comment by GaryHughes** [comment]
I plan to add a setting for different output formats, the default will be the current format and I'll add a CSV format which will look like the following. 

ExecutionReport
{
    BodyLength,9,374,,Length,
    MsgType,35,8,ExecutionReport,String
}

Please let me know if that looks ok.

**Comment by veltmannb** [comment]
Looks fine by me.

**Comment by GaryHughes** [comment]
The existing command has been renamed to 'FIX Master - Pretty Print'
I've added a new command called 'FIX Master - CSV Format' that produces the output described above.
