### ISSUE TITLE
Preview Window

### ISSUE THREAD

**Issue by harleybl** [GaryHughes/FixMaster#26]
Gary,

First I just want to say thank you for developing this plugin. It is awesome. I even wrote about it on Dev.to - https://dev.to/harleybl/fix-master-is-awesome-1oin. As someone who spends a fair amount of time troubleshooting FIX issues, this is a huge help.

It would be nice if there was a preview window where you could right-click (or just click) on a line in a FIX file and a preview window would just pretty print that message and show it to you. I envision it working similarly to when you right-click on a class and click "Peek Definition" and it shows you where that class is defined. 

Thanks,
Harley

**Comment by GaryHughes** [comment]
Thanks for the comments Harley! That's a good suggestion, I'll have a look at adding it.

**Comment by GaryHughes** [comment]
I've implemented this by using the builtin hover based tooltips, by default the pretty printed messages will be displayed in a tooltip requiring no clicks or commands etc and it's simple to move around a file. Please check the changelog for extra usage hints.

**Comment by harleybl** [comment]
Sweet. I can't wait to try it out.
