### ISSUE TITLE
Unable to load QuickFix Data Dictionary Path

### ISSUE THREAD

**Issue by steeveegee** [GaryHughes/FixMaster#29]
Using Windows and the QuickFix dictionary is located here
C:\QuickFix\resources\dictionary

However if I entered that in the settings I get 
Loading the QuickFix data dictionary 
and it gets stuck. The action never finishes loading. 

I've tried different variations:
"C:\QuickFix\resources\dictionary"
C:/QuickFix/resources/dictionary
C://QuickFix//resources//dictionary
"C://QuickFix//resources//dictionary"

Any suggestions on how the path should be entered?

**Comment by GaryHughes** [comment]
Are you able to attach your xml file? is 'dictionary' the name of the file? The path should be the complete path to a file.

eg. C:\QuickFix\resources\dictionary\file.xml

In any case it should give you more helpful feedback so I'll do some testing as well.

**Comment by steeveegee** [comment]
Thanks Gary. 
That's where I went wrong. I assumed it took in the dictionary directory not the file. 

Have corrected and it's working now. 

Still quite new to the extension but loving the idea already, so thanks for working on this. 

Is there a way to re-serialise the FIX message after Pretty Print? (happy to submit a new request)

**Comment by GaryHughes** [comment]
Great! As long as you haven’t saved you can just ctrl-z to undo the formatting. It shouldn’t be hard to reserialise a pretty printed file so I’ll consider it you submit a request.
