### ISSUE TITLE
No output from v1.6.1

### ISSUE THREAD

**Issue by rosstechldn** [GaryHughes/FixMaster#31]
Hi Guys,

Trying to get v1.6.1 of the plugin to format a simple one line fix 4.4 message;

`8=FIX.4.4^A9=649^A35=W^A34=975200^A49=CfhDemoPrices^A52=20210430-18:22:10.527^A56=BidX_Demo^A55=EURAUD^A262=1125141337578938370^A268=10^A269=0^A270=1.55962^A271=500000^A290=1^A64=20210504^A278=11/26-914418^A269=0^A270=1.55961^A271=500000^A290=2^A278=11/26-914419^A269=0^A270=1.55959^A271=2000000^A290=3^A278=11/26-914420^A269=0^A270=1.55958^A271=2000000^A290=4^A278=11/26-914421^A269=0^A270=1.55956^A271=2000000^A290=5^A278=11/26-914422^A269=1^A270=1.55976^A271=1000000^A290=1^A278=11/26-914423^A269=1^A270=1.55977^A271=3000000^A290=2^A278=11/26-914424^A269=1^A270=1.55979^A271=500000^A290=3^A278=11/26-914425^A269=1^A270=1.5598^A271=2500000^A290=4^A278=11/26-914426^A269=1^A270=1.55985^A271=2000000^A290=5^A278=11/26-914427^A10=045^A`

I select the above fix msg text, right click and i see 2 options in the pop up menu;
**Fix Master - CSV format selection**
**Fix Master -  Pretty Print Selection**

If i select either method, the same result is returned. No output at all.

A message from within VSCode appears briefly:
**"Finding and formatting fix messages"**

However, there is no output.

Can someone please advise?

VSCode version (mac);

Version: 1.55.2 (Universal)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (2 wks ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.4.0

**Comment by GaryHughes** [comment]
Hi, suspect it's a problem with your field separators. In the sample you've included the separator character is printed as ^A which is a common rendering of the control character 0x01. The parser expects the literal 0x01 to be present so this looks like a side effect of copy pasting the message.

If you do a search and replace for the string ^A with | and then in the fix master settings change the field separator to | then the pretty printer works as expected.

**Comment by rosstechldn** [comment]
Thank you Gary, this worked.
