### ISSUE TITLE
Settings does not seem to support VSCode variable interpolation

### ISSUE THREAD

**Issue by gnbond** [GaryHughes/FixMaster#41]
If I try and set the quickFixDataDictionaryPath to a workspace-relative path `${workspaceFolder}/dir/fields.xml` I get a "file not found" error.  If I use an absolute path `/home/user/workspace/dir/fields.xml` this is found and works great.

Would be handy if the path-based settings could honour these variables.

**Comment by GaryHughes** [comment]
There is apparently no API to do this nicely, I do see a way to do it manually for ${workspaceFolder} in [this extension](https://github.com/xaverh/vscode-clang-format/blob/master/src/extension.ts) is that enough for now?

**Comment by gnbond** [comment]
That would be fine for my purposes.... needing absolute paths is a pain when working in containers
