### ISSUE TITLE
Warn the user if they attempt to save a pretty printed log over the top of the original file

### ISSUE THREAD

**Issue by GaryHughes** [GaryHughes/FixMaster#42]

**Comment by gnbond** [comment]
I noticed this most when quitting VSCode with a pretty-printed window open.  On restart, the file had been overwritten.

Another possible and perhaps cleaner solution is to do the pretty print not into the existing buffer but into a new buffer not associated with a file, and leave the original buffer/file alone.

**Comment by GaryHughes** [comment]
A new buffer is a good idea, I'll experiment with that and see how it looks.
