### ISSUE TITLE
[Suggestion] Open parsed FIX message into the same editor as option

### ISSUE THREAD

**Issue by ncury** [GaryHughes/FixMaster#48]
I see that this was changed on 2.0.0 but as sometimes I have to check multiple messages, my editor gets clogged because it always opens a new window when I parse a message.

Is there anything we can do to enable an option in the plugin settings to disable the parsed message into a new window?

**Comment by GaryHughes** [comment]
I did consider this when I made the change, there were some issues doing this but I can't remember the details. I'll go back and review, would it be acceptable to have all formatted messages go into a single second window? Each time you format a message from the source log the formatted output just gets appended to the other window content? I can make this configurable.

**Comment by ncury** [comment]
It makes more sense (at least when I'm debugging multiple messages on one transaction, for example).
If it's an option (and easily doable) it's perfect :) I had to downgrade to 1.7 something so I didn't end with more than 20 new tabs at the end of the day

Thanks Gary!
